name = "GenomicBreedingCrossing"
uuid = "64bf6d4c-56b8-4980-8e2b-fc7044c470e1"
version = "1.0.0-DEV"
authors = ["jeffersonparil@gmail.com"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GenomicBreedingCore = "50d95318-1838-4cfa-a614-3543b4bb0509"
GenomicBreedingIO = "f6f5bf5f-7369-4de1-9a2f-51e3ce5e0754"
GenomicBreedingModels = "a21a2f6e-06ad-4936-9990-fa46b058b9d4"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
GenomicBreedingCore = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingCore.jl"}
GenomicBreedingIO = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingIO.jl"}
GenomicBreedingModels = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingModels.jl"}

[compat]
CairoMakie = "0.14.0"
ColorSchemes = "3.31.0"
DataFrames = "1.8.1"
Distributions = "0.25.123"
GenomicBreedingCore = "0.2.0"
GenomicBreedingIO = "0.2.0"
GenomicBreedingModels = "0.2.0"
JLD2 = "0.5.15"
MultivariateStats = "0.10.4"
Random = "1.11.0"
StatsBase = "0.34.10"
UnicodePlots = "3.8.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
